### ISSUE TITLE
Signal handling for sleep

### ISSUE THREAD

**Issue by azrle** [kazuho/p5-Server-Starter#44]
@kazuho 

We observed that `KILL_OLD_DELAY` may be interrupted by signal while waiting for new workers, using Perl 5.16, Linux.

``` perl
sleep $kill_old_delay;
```

As far as I know, `sleep` can be interrupted and Perl will not call the system call (in our environment, implemented by `nanosleep`) again for rest of seconds.

As a result, in some use cases, old workers are unexpectedly killed before new workers become capable to accept requests.
For example,
- try to reload env while waiting for new workers
- reload codes while waiting for new workers

Is it by design?
Or is it okay to fix it by sleeping again for rest of seconds when it was interrupted?

**Comment by kazuho** [comment]
Thank you for opening the issue.

> Or is it okay to fix it by sleeping again for rest of seconds when it was interrupted?

I think this is the right thing to do.

**Comment by azrle** [comment]
Thanks.
I would send a PR recently. :)

**Comment by azrle** [comment]
@kazuho I have sent a pull request https://github.com/kazuho/p5-Server-Starter/pull/45. Please check it.

Thanks.

**Comment by azrle** [comment]
See it in [0.33](https://github.com/kazuho/p5-Server-Starter/releases/tag/0.33). :)
