### ISSUE TITLE
Option to dæmonize

### ISSUE THREAD

**Issue by ap** [kazuho/p5-Server-Starter#6]
It would be nice to be able to pass `--daemon` to `start_server` so I don’t have to monkey around with external solutions, as I essentially end up having to recode the `start_server` script.

Additionally, if Server::Starter supported this directly/itself, then it could implement it in such a way that it does not fully background itself before the worker process has either started up successfully or failed, so that the foreground process can exit with a meaningful status. That is very useful in deploy scripts.

(I took a stab at this myself, but IPC is not my strong suit and as yet it doesn’t work.)

**Comment by kazuho** [comment]
I might have been too narrow-minded by making this decision.

Now _I_ want to daemonize a process, at the same time using Server::Starter for restarting it.

**Comment by ap** [comment]
:smile:

**Comment by kazuho** [comment]
@ap 
> Additionally, if Server::Starter supported this directly/itself, then it could implement it in such a way that it does not fully background itself before the worker process has either started up successfully or failed, so that the foreground process can exit with a meaningful status.

Regarding this point, I would suggest testing configuration / acquiring resources necessary for running the worker process before invoking `start_server`.

For example, when started with `--mode=master`, [h2o](https://github.com/h2o/h2o) runs configuration tests at first, then execs `start_server` which binds to TCP ports and then in turn invokes `h2o` with `--mode=worker`.
